# Generated by Django 3.2.8 on 2021-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Titulo de la pelicula')),
                ('Sinopsis', models.TextField(max_length=1000, verbose_name='Sinopsis')),
                ('duracion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Indicar el tiempo en horas')),
                ('tamaño', models.CharField(max_length=50, verbose_name='Definir tamaño de la pelicula')),
                ('poster', models.ImageField(null=True, upload_to='posters/peliculas/', verbose_name='Poster de la pelicula')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
    ]
