# Generated by Django 3.2.8 on 2021-10-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20211020_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='tamaño',
            new_name='tamanio',
        ),
    ]
